### ISSUE TITLE
ListView from java List

### ISSUE THREAD

**Issue by JFronny** [jwharm/java-gi#20] opened 2022-12-04 20:03 UTC
This is something for which java-gtk has a [utility class](https://github.com/bailuk/java-gtk/blob/main/java-gtk/src/main/java/ch/bailu/gtk/lib/bridge/ListIndex.java).
Something similar for this library would be nice.

**Comment by JFronny** [comment] 2022-12-17 21:43
I tried implementing this [here](https://git.frohnmeyer-wds.de/JfMods/Inceptum/src/branch/java-gi/launcher-gtk/src/main/java/io/gitlab/jfronny/inceptum/gtk/util/ListIndex.java), but obviously did something wrong, as the VM segfaults shortly after startup.
(It does work when I remove the list, so the rest of the UI likely isn't the cause)

**Comment by jwharm** [comment] 2022-12-28 20:44
I added functionality to generate setters for callbacks, including an auto-generated type definition for the callback. This should simplify some of the code in your ListIndex class (no need to write the `...Calback` types anymore).

I wanted to test your utility class, but I know almost nothing about the ListView API, so I don't know how to integrate the class into a small application. Do you have an easily reproducable example that I can use to find the cause of the segfault?

**Comment by JFronny** [comment] 2022-12-28 21:53
I added my ListIndex to this branch with an example: https://github.com/jwharm/java-gi/tree/example-20
There seems to be an issue with the callback gen preventing me from doing more testing.
Sorry for accidentally pushing to main, btw. Maybe you can force-push the accidental commits out.

**Comment by jwharm** [comment] 2022-12-29 17:00
I've tried to find out what is causing the crash, but cannot find it. There's a number of critical errors from GLib that the `get-type` property is set twice, but I cannot find why that is.

I'm wondering what the purpose of the `ListIndex` class is exactly. It is a `ListModel` but `getItem` returns a new `ListIndex` instance. Why would the model return an instance of itself? The original bailuk class also does this, but I don't understand the reason. Which makes it hard for me to reason about the way it works...

**Comment by jwharm** [comment] 2022-12-29 17:04
On a positive note, most of the initial setup of the new `ListIndex` type (the class and interface declaration, installing the property) seems to work fine. I suspect the crash is caused somewhere in the interaction between the `ListView` and the `ListIndex`.

**Comment by jwharm** [comment] 2022-12-29 17:09
I also tried to add `implements ListModel` on top of the `ListIndex` class, not because it's strictly neccessary, but because it *should* work, so why not.
It didn't work immediately because one method (I think it was `getItem`) has a wrong return type. I checked the GIR file and this method needed to be replaced with another one (specified with the `shadowed-by` attribute) that does have the correct signature. I added that to the GIR parser so that should be fixed now (on the `main` branch). I didn't have time anymore to merge that change into the `example-20` branch though.

**Comment by jwharm** [comment] 2023-01-04 21:00
I created a new listmodel implementation that can be used with any Java data structure. It is split into a `ListIndexModel class` and a `ListIndexItem`. See branch `example-20-fixed`.

The example works now, but only when I disable automatic reference counting for GObjects. (removed the call to `g_object_unref` in `ObjectBase` class.) It seems that the `ListIndexItems` get two Cleaners assigned and are subsequently unref'ed twice. I've temporarily disabled the call to `g_object_unref` and it works.

**Comment by jwharm** [comment] 2023-01-09 22:24
I've fixed the reference counting issue with #29. The example ListView implementation has been merged into the main branch. I'm closing the issue.

**Comment by JFronny** [comment] 2023-01-10 20:55
This implementation causes a NPE if the ListIndexModel size is 0.
To test this, you can just remove [this line](https://github.com/jwharm/java-gi/blob/3dff5ee5a151267c37bfc69d7568349b1d674153/example/src/main/java/io/github/jwharm/javagi/example/Gtk4ListViewExample.java#L66).

**Comment by jwharm** [comment] 2023-01-11 21:12
This has been fixed with commit [5d53a58](https://github.com/jwharm/java-gi/commit/5d53a5829ea9ebe310a64ed921f05b76b3923038).

**Comment by JFronny** [comment] 2023-01-12 14:15
I once again came across an issue with this: The java-gtk implementation allows re-setting the size to update elements of the list view.
I have updated the example class to demonstrate this: https://github.com/jwharm/java-gi/tree/regenerate
The effect is especially clear when removing the generateList call from the example constructor, since the Generate button will seem to do nothing.

**Comment by jwharm** [comment] 2023-01-12 21:09
Thanks for the bug reports.

I forgot to emit the `items-changed` signal in `setSize`. It's fixed now in the `regenerate` branch.

**Comment by jwharm** [comment] 2023-01-17 19:32
Fixed with commit [8e5650a](https://github.com/jwharm/java-gi/commit/8e5650af08c1df1212d57b8e7066a81e2a14e98d)

**Closed by jwharm** 2023-01-17 19:32 UTC
