### ISSUE TITLE
Cannot create gtk4-layer-shell binding using the new cli generator.

### ISSUE THREAD

**Issue by poach3r** [jwharm/java-gi#159] opened 2024-12-03 23:34 UTC
Hello, as the title suggests I'm attempting to build gtk4-layer-shell using the newly added generator described in #156, however I'm getting an error.

Command:
```
./generator/build/install/java-gi/bin/java-gi -p ~/gtk4-layer-shell/build/src/Gtk4LayerShell-1.0.gir
```

Error:
```
java.lang.NullPointerException: Cannot invoke "String.length()" because "plainText" is null
	at info.picocli@4.7.6/picocli.CommandLine$Help$ColorScheme.apply(CommandLine.java:17672)
	at info.picocli@4.7.6/picocli.CommandLine$Help$ColorScheme.errorText(CommandLine.java:17548)
	at io.github.jwharm.javagi.generator/io.github.jwharm.javagi.JavaGI.handleException(JavaGI.java:138)
	at info.picocli@4.7.6/picocli.CommandLine.execute(CommandLine.java:2184)
	at io.github.jwharm.javagi.generator/io.github.jwharm.javagi.JavaGI.main(JavaGI.java:126)
```

**Comment by jwharm** [comment] 2024-12-04 07:06
That shouldn't happen.
Can you attach the `Gtk4LayerShell-1.0.gir` file please?

**Comment by poach3r** [comment] 2024-12-04 12:15
Sure, I built this using the instructions on their Github repo on Debian Linux.
[Gtk4LayerShell-1.0.gir.zip](https://github.com/user-attachments/files/18007851/Gtk4LayerShell-1.0.gir.zip)

**Comment by jwharm** [comment] 2024-12-04 19:17
The issue was caused by a change I merged a few days ago. It's fixed now. Apologies for the inconvenience.

**Closed** 2024-12-04 19:16 UTC
Labels: bug
